import {
  User,
  Product,
  Subscription,
  Crate,
  Order,
  OrderPaymentMethod,
  CrawlStatus,
  CurrencyConfig,
  OrderTx,
  Currency,
  Wallet,
  WalletBalance,
  WalletLog,
  Webhook,
  WebhookLog,
  WebhookProgress,
  Withdrawal,
  WithdrawalLog,
  WithdrawalTx,
  EventLog,
  EnvConfig,
  Address,
  LocalTx,
  EventTakeOrder,
  EventPlaceOrder,
  HotWallet,
} from 'src/database/entities';
import { ConnectionOptions } from 'typeorm';

export const databaseConfig: ConnectionOptions = {
  type: (process.env.TYPEORM_CONNECTION || 'mysql') as any,
  host: process.env.TYPEORM_HOST || 'localhost',
  port: parseInt(process.env.TYPEORM_PORT) || 3306,
  username: process.env.TYPEORM_USERNAME || 'root',
  password: process.env.TYPEORM_PASSWORD || '1',
  database: process.env.TYPEORM_DATABASE || 'fasty',
  entities: [
    User,
    Product,
    Subscription,
    Crate,
    Order,
    OrderTx,
    OrderPaymentMethod,
    CrawlStatus,
    CurrencyConfig,
    Currency,
    Wallet,
    WalletBalance,
    WalletLog,
    Webhook,
    WebhookLog,
    WebhookProgress,
    Withdrawal,
    WithdrawalLog,
    WithdrawalTx,
    EventLog,
    EnvConfig,
    Address,
    LocalTx,
    EventTakeOrder,
    EventPlaceOrder,
    HotWallet,
  ],
  synchronize: true,
};
